include("YQ.jl")
using .YQ

mps = MPSState(3)
applyGate!(mps, XGate(1))
applyGate!(mps, XGate(2))
# applyGate!(mps, ToffoliGate([1,2,3]))
# print(mps,"\n======\n")

# exact = ExactState(3)
# applyGate!(exact, XGate(1))
# applyGate!(exact, XGate(2))
# applyGate!(exact, ToffoliGate([1,2,3]))
	applyGate!(mps, HGate(3))
	applyGate!(mps, CNOTGate(2,3))
	applyGate!(mps, TdagGate(3))
	applyGate!(mps, CNOTGate(1,3))
	applyGate!(mps, TGate(3))
	applyGate!(mps, CNOTGate(2,3))
	applyGate!(mps, TdagGate(3))
	applyGate!(mps, CNOTGate(1,3))
	applyGate!(mps, TGate(3))
	applyGate!(mps, HGate(3))
	applyGate!(mps, TdagGate(2))
	applyGate!(mps, CNOTGate(1,2))
	applyGate!(mps, TdagGate(2))
	applyGate!(mps, CNOTGate(1,2))
	applyGate!(mps, TGate(1))
	applyGate!(mps, SGate(2))

	# applyGate!(mps, HGate(3))
	# applyGate!(mps, CNOTGate(2,3))
	# applyGate!(mps, TdagGate(3))
	# applyGate!(mps, CNOTGate(1,3))
	# applyGate!(mps, TGate(3))
	# applyGate!(mps, CNOTGate(2,3))
	# applyGate!(mps, TdagGate(3))
	# applyGate!(mps, CNOTGate(1,3))
	# applyGate!(mps, TGate(3))
	# applyGate!(mps, HGate(3))
	# applyGate!(mps, TdagGate(2))
	# applyGate!(mps, CNOTGate(1,2))
	# applyGate!(mps, TdagGate(2))
	# applyGate!(mps, CNOTGate(1,2))
	# applyGate!(mps, TGate(1))
	# applyGate!(mps, SGate(2))

	# applyGate!(mps, HGate(3))
	# applyGate!(mps, CNOTGate(2,3))
	# applyGate!(mps, TdagGate(3))
	# applyGate!(mps, CNOTGate(1,3))
	# applyGate!(mps, TGate(3))
	# applyGate!(mps, CNOTGate(2,3))
	# applyGate!(mps, TdagGate(3))
	# applyGate!(mps, CNOTGate(1,3))
	# applyGate!(mps, TGate(3))
	# applyGate!(mps, HGate(3))
	# applyGate!(mps, TdagGate(2))
	# applyGate!(mps, CNOTGate(1,2))
	# applyGate!(mps, TdagGate(2))
	# applyGate!(mps, CNOTGate(1,2))
	# applyGate!(mps, TGate(1))
	# applyGate!(mps, SGate(2))
orderQubits!(mps)
# net = ITensorNet(mps.sites)
print(prod(mps.sites))
# print(exact)

